name: Build image and push it to DockerHub

on:
  pull_request:
    branches:
      - main 

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t kushrohra/kushrohra_assignment3_solution .
      
      - name: Push Docker image
        run: docker push kushrohra/kushrohra_assignment3_solution