name: Pull and Test Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  check_placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Check Placeholder
        run: echo "This is a placeholder job"

  pull_and_test:
    runs-on: ubuntu-latest
    needs: check_placeholder
    if: success() == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set success flag
        if: success() == 'true'
        id: set_success
        run: echo "BUILD_AND_PUSH_SUCCESS=true" >> $GITHUB_ENV

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Pull Docker image
        run: docker pull kushrohra/kushrohra_assignment3_solution

      - name: Run Docker container and test score
        run: |
          docker run --rm kushrohra/kushrohra_assignment3_solution

      - name: Set success output
        if: success() == 'true'
        run: echo "::set-output name=success::true"
