name: Pull and Test Docker Image

on:
  pull_request:
    branches:
      - main  # Adjust if your main branch has a different name

jobs:
  pull_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull kushrohra/kushrohra_assignment3_solution

      - name: Run Docker container and test score
        run: |
          docker run --rm kushrohra/kushrohra_assignment3_solution
