name: Pull and Test Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  pull_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull kushrohra/kushrohra_assignment3_solution

      - name: Run Docker container and test score
        run: |
          docker run --rm kushrohra/kushrohra_assignment3_solution
