name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  pull_and_test:
    runs-on: ubuntu-latest
    needs: Train
    if: success('Train') == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Pull Docker image
        run: docker pull kushrohra/kushrohra_assignment3_solution

      - name: Run Docker container and test score
        run: |
          score=$(docker run --rm kushrohra/kushrohra_assignment3_solution)
          echo "::set-output name=score::$score"
          if [[ `echo "$score 0.30" | awk '{print ($1 < $2)}'` == 1 ]]; then
            echo "Insufficient Accuracy"
            exit 1
          fi

functions:
  success:
    description: Check if the Train job was successful
    returns: 'true' if successful, otherwise 'false'
    runs: |
      return ${{ job.status }} == 'completed' && steps.Train.outcome == 'success'
